### ISSUE TITLE
Need windows versions?

### ISSUE THREAD

**Issue by hugheaves** [MAVProxyUser/DJIAssistant2Binaries#1]
I know someone who has Windows versions 1.0.5 - 1.0.9 inclusive. If that would be helpful, let me know.

**Comment by MAVProxyUser** [comment]
yes by all means...

**Comment by nezarbeidas** [comment]
if you need windows versions before the 1.0.5 please let me know

**Comment by MAVProxyUser** [comment]
Please share links to any binaries you have and I will get them included.

**Comment by nezarbeidas** [comment]
i sent you an email for the files i found in my computer so far

**Comment by droner69** [comment]
Versions 1.0.5 - 1.1.2 are located at [https://github.com/droner69/MavicPro/tree/master/DJI_Assistant_2_Binaries_Windows](https://github.com/droner69/MavicPro/tree/master/DJI_Assistant_2_Binaries_Windows).  I'm only missing 1.0.6 and 1.0.9-2.

**Comment by nezarbeidas** [comment]
@MAVProxyUser i uploaded 1.0.6 and 1.0.9 to the same google drive link i sent you by email.

**Comment by MAVProxyUser** [comment]
This has been sorted out... please submit Pull requests if you have any more missing binaries. 
https://github.com/MAVProxyUser/DJIAssistant2Binaries/commit/44436e9cb66118d9fa2400fc35a1703c109fbd61
